### ISSUE TITLE
'cache/sub_obj_wds/refcoco_unc/sub_obj.json' not found

### ISSUE THREAD

**Issue by HubHop** [GingL/KPRN#1]
Hi,

Thanks for your excellent work! 

I'm trying to run your code, but I found this error when I was generating semantic similarity and word embedding file. Could you tell me where I can find this file?

Logs:

parsed input parameters:
{
  "output_json": "similarity.json",
  "data_root": "data",
  "dataset": "refcoco",
  "splitBy": "unc",
  "max_length": null,
  "images_root": "",
  "word_count_threshold": 5,
  "topK": 50
}
Loader loading subject and object words: cache/sub_obj_wds/refcoco_unc/sub_obj.json
Traceback (most recent call last):
  File "/snap/pycharm-professional/173/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/173/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data1/newwork_reg/KPRN/tools/prepro_sim.py", line 244, in <module>
    main(params)
  File "/data1/newwork_reg/KPRN/tools/prepro_sim.py", line 176, in main
    sub_obj_wds_info = json.load(open(sub_obj_wds))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/sub_obj_wds/refcoco_unc/sub_obj.json'

Process finished with exit code 1

**Comment by GingL** [comment]
I have added the prepro_sub_obj_wds.py. You can run it to get the files.

**Comment by HubHop** [comment]
Hi @GingL, thanks for your quick reply, the new script you just uploaded solves the issue in the title, but I met another error as below,

parsed input parameters:
{
  "output_json": "similarity.json",
  "data_root": "data",
  "dataset": "refcoco",
  "splitBy": "unc",
  "max_length": null,
  "images_root": "",
  "word_count_threshold": 5,
  "topK": 50
}
Loader loading subject and object words: cache/sub_obj_wds/refcoco_unc/sub_obj_wds.json
Loader loading data.json:  cache/prepro/refcoco_unc/data.json
Traceback (most recent call last):
  File "/snap/pycharm-professional/173/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/173/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data1/newwork_reg/KPRN/tools/prepro_sim.py", line 244, in <module>
    main(params)
  File "/data1/newwork_reg/KPRN/tools/prepro_sim.py", line 179, in main
    info = json.load(open(data_json))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/prepro/refcoco_unc/data.json'

I notice that 'data.json' can be generated by the script 'prepo.py' in MAttNet, may I ask whether you generate 'data.json' in the same way?

**Comment by GingL** [comment]
Yes. You can just follow MAttNet to prepare the features.

**Comment by HubHop** [comment]
Cheers, thank you so much!
